name: 02-climate-keingtobin
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13
  - jupyter

  # All packages imported in notebooks
  # Part 2
  - pandas
  - earthpy

  # Part 5
  - matplotlib
  - seaborn
  - scikit-learn
  - hvplot